redis:
  host: redis
  port: :6379
  user: default    # Добавь эту строку, если твой код умеет её читать
  password: "password" # Оберни в кавычки на всякий случай
server:
  http:
    domain: wcow4w4gg00cww80w8gggggg.45.130.42.231.sslip.io
    http_address: :80
    https_address: :443
  grpc:
    domain: wcow4w4gg00cww80w8gggggg.45.130.42.231.sslip.io
    address: :50051