redis:
  host: redis
  port: :6379
  password: password # Должен совпадать с паролем в docker-compose

server:
  http:
    domain: wcow4w4gg00cww80w8gggggg.45.130.42.231.sslip.io/
    http_address: :8080    # Меняем на 8080, чтобы не драться с Coolify за 80 порт
    https_address: ""      # Оставляем пустым! SSL возьмет на себя Coolify
  grpc:
    domain: wcow4w4gg00cww80w8gggggg.45.130.42.231.sslip.io/
    address: :50051