redis:
  host: redis
  port: :6379
  password: pass
server:
  http:
    domain: wcow4w4gg00cww80w8gggggg.45.130.42.231.sslip.io
    http_address: :80
    https_address: "" # ОБЯЗАТЕЛЬНО ПУСТО!
  grpc:
    domain: wcow4w4gg00cww80w8gggggg.45.130.42.231.sslip.io
    address: :50051